### ISSUE TITLE
Update to 2.1.0

### ISSUE THREAD

**Issue by tomasff** [SecurityAddicted/pineapple-ar150#18]
Can you please upgrade to the new firmware version 2.1.0?

**Comment by mankidavu** [comment]
I built a new one following the instructions. It did flash successfully and my TP Link adapted also works good. But pineap is not starting. So recon also not working. I can see naming of wlan1 is correct. Another need is to add the getDevice fix Alex mentioned. Would like to know how to fix that so that modules can be downloaded.

**Comment by MR5A1NT** [comment]
I'm also having the same issue, not sure what the problem is yet...
To fix internet connecting, modules etc edit the file `/pineapple/api/pineapple.php` remove lines 110 through to 120 and replace with

 `function getDevice ()
{
    return 'nano';
}`

**Comment by crazyquark** [comment]
`pineapd` is crashing with Segmentation fault; I am unable to determine the cause - maybe a missing lib? Also CPU usage is crazy high. Looks like they merged the firmwares of the nano and tetra and ported the tools. Before, PineAP was just using hostapd.

**Comment by crazyquark** [comment]
One cool thing I noticed(on 2.0.2 actually) is that the network is configured to use a second eth interface if it exists. So if you plug the other port into your router you'll get internet on pineapple without needing ICS.

**Comment by mankidavu** [comment]
This pineapd issue was fixed. Needed few kernel config. Works fine now.New versions work fine now.

**Comment by careyer** [comment]
@mankidavu : Awesome! Is there a way to download the fixed version somewhere? Any drawbacks for the 2.02 remaining?

**Comment by mankidavu** [comment]
> 
> 
> @mankidavu : Awesome! Is there a way to download the fixed version somewhere? Any drawbacks for the 2.02 remaining?

I think, I have to now clone this repo and start building one again, as no one is releasing.

pineapd issue was due to kernel options. blu3b0x fixed that on some other place/discussions thread.
What I remember is POSIX_MQUEUE values were added to kernel config.

CONFIG_POSIX_MQUEUE=y
CONFIG_POSIX_MQUEUE_SYSCTL=y

I have moved to other projects and stopped giving too much time on this one.

No drawbacks. But as you know new versions are always more bug fixed and more good. :)

**Comment by careyer** [comment]
Thanks! 
I (and most likely others) would be grateful to have a fixed v2.x version finally. Would be great if you forked the repo and could build and provide a ready to flag bin file.

Thanks for your effort.
Best
Thomas 

Von meinem iPhone gesendet
